notifications:
  email: false
sudo: required
matrix:
 include:
 - os: osx
   language: generic
   env: MAC_PYTHON_VERSION=3.6
 - os: osx
   language: generic
   env: MAC_PYTHON_VERSION=3.7
 - os: linux
   language: python
   python: 3.6
before_install:
# install other dependencies
- source ./.travis/${TRAVIS_OS_NAME}_setup_python.sh $MAC_PYTHON_VERSION
install:
# install binary packages
- travis_retry pip install --upgrade pip
- travis_retry pip install setuptools wheel
- travis_retry pip install git+git://github.com/ZELLMECHANIK-DRESDEN/dclab.git
- travis_retry pip install -e .
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
- coverage run --source=dclab setup.py test
- coverage report -m
- codecov
- flake8 dclab
- flake8 examples
- flake8 tests
after_success:
- codecov
before_deploy:
- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: "ci_zmdd"
  password:
    secure: "qWKJaxCXot/2I6ZbsamNzcFQBjkzSTEhbKuTbU+4Yz6sYYXHbDCvC4YdgMtL2Zt9yoH9ZFoyxUk2YH72opL5WxvZZYsld/d063M7WabCw6qjhFRuK+Q8UzsWqmT9p+48u0yUl4hOPyOalu6G9hZ/c+Hl5hOrVVFfLHpZyXa4Sp1SRWxe/YTLXDmy7Lqa5WyD6kTterrwcTbe9wUGzysw/FJ5Tvik7RmJ57U3fBWdQpCte5Z/lAY/WT758kWYoRc6xCH7auFoXXT+K4libSK7EADBICaiuTz/j9ouN/GdWUR0hVvFn7EUqIFPdmlk5tIHczQ3udXsE1Xepz8HyIVeeNMiusmnsNOO5bb/Oc48MKfh6u6mloprODfYV7n4GWcsSNzyex494qQYhy9U0F9VP77RBSyMNKeTTnBydmUeA6apDe2pEBBXDOCVWneK+MQLawgAdGC7Q6iQ7tfN8HhQosMUyAd890H1FLXqdmpQaop93Emh1pdWLlvGgaNLEZFtAodVybizwXFO3ow+kIMbox/vVWcj5TT7gOQJIVR5tRTW8Ux+UUhzE2ZcFQ8pQbdenxCxfcG2GLWVSIj7svJf4YSgse4FOERROuWfGvO5mDDmEgpC0uVmLrSY4j4WCJHc2OkbvMqmJoQaXFk8iQ2ewegvRrp2HglESjgFgEOFCrw="
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
